const DEFAULT_TOPICS = {
  Facturacion: [
    'Pagos y Finanzas: cobros, facturas, reembolsos de dinero, precios y suscripciones.',
    'Problemas con cargos de dinero en la tarjeta, Stripe o transferencia bancaria.',
    'Factura fiscal, recibo de compra sin impuestos, desglose de IVA o proforma.',
    'El recibo que me enviaron no tiene el desglose de impuestos o el IVA.',
    'Cargo doble de dinero, precio que ha subido sin aviso o error en el monto cobrado.',
    'Actualizar datos de facturacion de la empresa o informacion de pago financiera.',
    'El enlace de pago ha expirado, error de validacion bancaria o pago fallido.',
    'Reembolso del pedido en mi cuenta bancaria o estado de cuenta financiera.',
    'No reconozco un cobro de dinero en mi extracto bancario o tarjeta de credito.',
  ],
  'Problema Tecnico': [
    'Fallas del sistema: errores, bugs, crashes, lentitud y mal funcionamiento tecnico.',
    'Tengo problemas con mi app, no funciona, se cierra sola o el boton no responde.',
    'Error de sistema, fallo tecnico del software o mal funcionamiento de la aplicacion.',
    'Error HTTP 500, 502, 504, Gateway Timeout o Database Connection Error.',
    'No recibo las notificaciones de escritorio que tengo configuradas en el sistema.',
    'El uso de memoria se dispara al 100%, carga de CPU alta o sistema congelado.',
    'Imagenes rotas, diseno malformado, enlaces que no cargan o UI defectuosa.',
    'No puedo subir archivos, se corta la conexion o el webhook falla al enviar datos.',
    'El buscador interno no devuelve resultados o el comando de despliegue da error.',
    'Falla el payload del webhook, falta un campo tecnico o error de sincronizacion.',
  ],
  'Acceso a Cuenta': [
    'Perfil de Usuario: login, entrar, contrasenas, perfiles, seguridad y acceso.',
    'No puedo iniciar sesion en mi perfil, usuario bloqueado o cuenta de acceso suspendida.',
    'Recibo avisos de inicio de sesion sospechosos o desde ubicaciones no reconocidas.',
    'No recibo el codigo SMS de verificacion, problemas con MFA, 2FA o FaceID.',
    'Mi aplicacion de autenticacion esta desincronizada o codigos de respaldo perdidos.',
    'Olvide mi clave de acceso o el cambio de contrasena no cumple los requisitos.',
    'Correo de restablecimiento de perfil no llega o enlace de confirmacion utilizado.',
    'Cambiar correo electronico del perfil, invitar colaboradores o gestionar equipo.',
    'Dispositivo no reconocido para el login o autenticacion de seguridad fallida.',
  ],
  'Solicitud de Funcion': [
    'Mejoras y Sugerencias: ideas, peticiones, nuevas caracteristicas y roadmap.',
    'Me gustaria anadir una funcion, herramienta o integracion (Salesforce, Notion).',
    'Modo oscuro, barra lateral colapsable, widgets nuevos o cambios de diseno.',
    'Modo offline para trabajar sin conexion, exportar datos o guardado automatico.',
    'Hoja de ruta para nuevas funciones, API para desarrolladores o aplicacion nativa.',
    'Implementar notificaciones push, roles granulares o buscador global avanzado.',
    'Permitir a los usuarios personalizar los widgets de su panel o escritorio.',
  ],
  'Consulta General': [
    'Informacion y Ayuda: dudas generales, documentacion, guias y tutoriales.',
    'Donde puedo encontrar los videos tutoriales para principiantes de su software?',
    'Horarios de atencion al cliente, foro de la comunidad, ventas y referidos.',
    'Programas para ONGs, instituciones educativas, becas o descuentos sociales.',
    'Guia de usuario en formato PDF para imprimir o manuales de ayuda descargables.',
    'Diferencia entre planes Pro/Enterprise, demos personalizadas y certificaciones.',
    'Terminos y condiciones, T&C, privacidad, legal, cumplimiento SOC2/HIPAA.',
    'Novedades de la ultima version, boletin de noticias, anuncios y guias de inicio.',
    'Politicas de retencion de datos, ubicacion de servidores y vision de la empresa.',
    'Tiempo de respuesta garantizado por el soporte o dudas sobre como empezar.',
  ],
};

module.exports = {
  DEFAULT_TOPICS,
};
